version: 2
jobs:
  quality_assurance:
    docker:
      - image: circleci/node:11.10.1

      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/

    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          keys:
            - dependencies-{{ checksum "yarn.lock" }}

      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile

      - save_cache:
          paths:
            - ./node_modules
          key: dependencies-{{ checksum "yarn.lock" }}

      - run:
          name: Run Linter
          command: "yarn lint"

      - run:
          name: Run Typescript compiler
          command: "yarn build"
workflows:
  version: 2
  test_and_build_images:
    jobs:
      - quality_assurance
